// --- VIETNAMESE VOCABULARY DATASET ---
    const rawQuestions = [
      // === CATEGORY: ANIMALS (50 Words) ===
      { id: "a_01", category: "animals", categoryLabel: "動物", jp: "犬", answer: "con chó", altAnswers: ["con cho"] },
      { id: "a_02", category: "animals", categoryLabel: "動物", jp: "猫", answer: "con mèo", altAnswers: ["con meo"] },
      { id: "a_03", category: "animals", categoryLabel: "動物", jp: "鳥", answer: "con chim", altAnswers: ["con chim"] },
      { id: "a_04", category: "animals", categoryLabel: "動物", jp: "魚", answer: "con cá", altAnswers: ["con ca"] },
      { id: "a_05", category: "animals", categoryLabel: "動物", jp: "牛", answer: "con bò", altAnswers: ["con bo"] },
      { id: "a_06", category: "animals", categoryLabel: "動物", jp: "豚", answer: "con heo", altAnswers: ["con lon", "con lợn"] },
      { id: "a_07", category: "animals", categoryLabel: "動物", jp: "ニワトリ", answer: "con gà", altAnswers: ["con ga"] },
      { id: "a_08", category: "animals", categoryLabel: "動物", jp: "アヒル / カモ", answer: "con vịt", altAnswers: ["con vit"] },
      { id: "a_09", category: "animals", categoryLabel: "動物", jp: "馬", answer: "con ngựa", altAnswers: ["con ngua"] },
      { id: "a_10", category: "animals", categoryLabel: "動物", jp: "虎 (トラ)", answer: "con hổ", altAnswers: ["con ho", "con cọp", "con cop"] },
      { id: "a_11", category: "animals", categoryLabel: "動物", jp: "ライオン", answer: "con sư tử", altAnswers: ["con su tu"] },
      { id: "a_12", category: "animals", categoryLabel: "動物", jp: "象 (ゾウ)", answer: "con voi", altAnswers: ["con voi"] },
      { id: "a_13", category: "animals", categoryLabel: "動物", jp: "猿 (サル)", answer: "con khỉ", altAnswers: ["con khi"] },
      { id: "a_14", category: "animals", categoryLabel: "動物", jp: "ネズミ", answer: "con chuột", altAnswers: ["con chuot"] },
      { id: "a_15", category: "animals", categoryLabel: "動物", jp: "ウサギ", answer: "con thỏ", altAnswers: ["con tho"] },
      { id: "a_16", category: "animals", categoryLabel: "動物", jp: "熊 (クマ)", answer: "con gấu", altAnswers: ["con gau"] },
      { id: "a_17", category: "animals", categoryLabel: "動物", jp: "蛇 (ヘビ)", answer: "con rắn", altAnswers: ["con ran"] },
      { id: "a_18", category: "animals", categoryLabel: "動物", jp: "羊 (ヒツジ)", answer: "con cừu", altAnswers: ["con cuu"] },
      { id: "a_19", category: "animals", categoryLabel: "動物", jp: "ヤギ", answer: "con dê", altAnswers: ["con de"] },
      { id: "a_20", category: "animals", categoryLabel: "動物", jp: "キリン", answer: "con hươu cao cổ", altAnswers: ["con huou cao co"] },
      { id: "a_21", category: "animals", categoryLabel: "動物", jp: "シマウマ", answer: "con ngựa vằn", altAnswers: ["con ngua van"] },
      { id: "a_22", category: "animals", categoryLabel: "動物", jp: "ラクダ", answer: "con lạc đà", altAnswers: ["con lac da"] },
      { id: "a_23", category: "animals", categoryLabel: "動物", jp: "カンガルー", answer: "con chuột túi", altAnswers: ["con chuot tui"] },
      { id: "a_24", category: "animals", categoryLabel: "動物", jp: "ワニ", answer: "con cá sấu", altAnswers: ["con ca sau"] },
      { id: "a_25", category: "animals", categoryLabel: "動物", jp: "カメ", answer: "con rùa", altAnswers: ["con rua"] },
      { id: "a_26", category: "animals", categoryLabel: "動物", jp: "カエル", answer: "con ếch", altAnswers: ["con ech"] },
      { id: "a_27", category: "animals", categoryLabel: "動物", jp: "サメ", answer: "con cá mập", altAnswers: ["con ca map"] },
      { id: "a_28", category: "animals", categoryLabel: "動物", jp: "クジラ", answer: "con cá voi", altAnswers: ["con ca voi"] },
      { id: "a_29", category: "animals", categoryLabel: "動物", jp: "イルカ", answer: "con cá heo", altAnswers: ["con ca heo"] },
      { id: "a_30", category: "animals", categoryLabel: "動物", jp: "タコ", answer: "con bạch tuộc", altAnswers: ["con bach tuoc"] },
      { id: "a_31", category: "animals", categoryLabel: "動物", jp: "エビ", answer: "con tôm", altAnswers: ["con tom"] },
      { id: "a_32", category: "animals", categoryLabel: "動物", jp: "カニ", answer: "con cua", altAnswers: ["con cua"] },
      { id: "a_33", category: "animals", categoryLabel: "動物", jp: "イカ", answer: "con mực", altAnswers: ["con muc"] },
      { id: "a_34", category: "animals", categoryLabel: "動物", jp: "ミツバチ", answer: "con ong", altAnswers: ["con ong"] },
      { id: "a_35", category: "animals", categoryLabel: "動物", jp: "チョウ (蝶)", answer: "con bướm", altAnswers: ["con buom"] },
      { id: "a_36", category: "animals", categoryLabel: "動物", jp: "アリ (蟻)", answer: "con kiến", altAnswers: ["con kien"] },
      { id: "a_37", category: "animals", categoryLabel: "動物", jp: "カ (蚊)", answer: "con muỗi", altAnswers: ["con muoi"] },
      { id: "a_38", category: "animals", categoryLabel: "動物", jp: "ハエ", answer: "con ruồi", altAnswers: ["con ruoi"] },
      { id: "a_39", category: "animals", categoryLabel: "動物", jp: "クモ (蜘蛛)", answer: "con nhện", altAnswers: ["con nhen"] },
      { id: "a_40", category: "animals", categoryLabel: "動物", jp: "ゴキブリ", answer: "con gián", altAnswers: ["con gian"] },
      { id: "a_41", category: "animals", categoryLabel: "動物", jp: "キツネ", answer: "con cáo", altAnswers: ["con cao"] },
      { id: "a_42", category: "animals", categoryLabel: "動物", jp: "オオカミ", answer: "con sói", altAnswers: ["con soi"] },
      { id: "a_43", category: "animals", categoryLabel: "動物", jp: "ワシ (鷲)", answer: "con đại bàng", altAnswers: ["con dai bang"] },
      { id: "a_44", category: "animals", categoryLabel: "動物", jp: "ハト (鳩)", answer: "con chim bồ câu", altAnswers: ["con chim bo cau"] },
      { id: "a_45", category: "animals", categoryLabel: "動物", jp: "フクロウ", answer: "con chim cú", altAnswers: ["con chim cu"] },
      { id: "a_46", category: "animals", categoryLabel: "動物", jp: "ペンギン", answer: "con chim cánh cụt", altAnswers: ["con chim canh cut"] },
      { id: "a_47", category: "animals", categoryLabel: "動物", jp: "パンダ", answer: "con gấu trúc", altAnswers: ["con gau truc"] },
      { id: "a_48", category: "animals", categoryLabel: "動物", jp: "サイ", answer: "con tê giác", altAnswers: ["con te giac"] },
      { id: "a_49", category: "animals", categoryLabel: "動物", jp: "カバ", answer: "con hà mã", altAnswers: ["con ha ma"] },
      { id: "a_50", category: "animals", categoryLabel: "動物", jp: "カタツムリ / 貝", answer: "con ốc", altAnswers: ["con oc"] },

      // === CATEGORY: JOBS (50 Words) ===
      { id: "j_01", category: "jobs", categoryLabel: "職業", jp: "医師 / ドクター", answer: "bác sĩ", altAnswers: ["bac si"] },
      { id: "j_02", category: "jobs", categoryLabel: "職業", jp: "看護師", answer: "y tá", altAnswers: ["y ta"] },
      { id: "j_03", category: "jobs", categoryLabel: "職業", jp: "教師 / 先生", answer: "giáo viên", altAnswers: ["giao vien", "thầy giáo", "cô giáo"] },
      { id: "j_04", category: "jobs", categoryLabel: "職業", jp: "生徒 / 児童", answer: "học sinh", altAnswers: ["hoc sinh"] },
      { id: "j_05", category: "jobs", categoryLabel: "職業", jp: "大学生", answer: "sinh viên", altAnswers: ["sinh vien"] },
      { id: "j_06", category: "jobs", categoryLabel: "職業", jp: "エンジニア", answer: "kỹ sư", altAnswers: ["ky su"] },
      { id: "j_07", category: "jobs", categoryLabel: "職業", jp: "プログラマー", answer: "lập trình viên", altAnswers: ["lap trinh vien"] },
      { id: "j_08", category: "jobs", categoryLabel: "職業", jp: "警察官", answer: "cảnh sát", altAnswers: ["canh sat", "công an"] },
      { id: "j_09", category: "jobs", categoryLabel: "職業", jp: "消防士", answer: "lính cứu hỏa", altAnswers: ["linh cuu hoa"] },
      { id: "j_10", category: "jobs", categoryLabel: "職業", jp: "軍人", answer: "bộ đội", altAnswers: ["bo doi", "quân nhân"] },
      { id: "j_11", category: "jobs", categoryLabel: "職業", jp: "弁護士", answer: "luật sư", altAnswers: ["luat su"] },
      { id: "j_12", category: "jobs", categoryLabel: "職業", jp: "裁判官", answer: "thẩm phán", altAnswers: ["tham phan"] },
      { id: "j_13", category: "jobs", categoryLabel: "職業", jp: "料理人 / シェフ", answer: "đầu bếp", altAnswers: ["dau bep"] },
      { id: "j_14", category: "jobs", categoryLabel: "職業", jp: "会社員 / オフィスワーカー", answer: "nhân viên văn phòng", altAnswers: ["nhan vien van phong"] },
      { id: "j_15", category: "jobs", categoryLabel: "職業", jp: "社長 / 支配人", answer: "giám đốc", altAnswers: ["giam doc"] },
      { id: "j_16", category: "jobs", categoryLabel: "職業", jp: "歌手", answer: "ca sĩ", altAnswers: ["ca si"] },
      { id: "j_17", category: "jobs", categoryLabel: "職業", jp: "俳優 / 女優", answer: "diễn viên", altAnswers: ["dien vien"] },
      { id: "j_18", category: "jobs", categoryLabel: "職業", jp: "画家 / イラストレーター", answer: "họa sĩ", altAnswers: ["hoa si"] },
      { id: "j_19", category: "jobs", categoryLabel: "職業", jp: "記者 / ジャーナリスト", answer: "nhà báo", altAnswers: ["nha bao"] },
      { id: "j_20", category: "jobs", categoryLabel: "職業", jp: "写真家 / カメラマン", answer: "nhiếp ảnh gia", altAnswers: ["nhiep anh gia"] },
      { id: "j_21", category: "jobs", categoryLabel: "職業", jp: "パイロット", answer: "phi công", altAnswers: ["phi cong"] },
      { id: "j_22", category: "jobs", categoryLabel: "職業", jp: "客室乗務員 (CA)", answer: "tiếp viên hàng không", altAnswers: ["tiep vien hang khong"] },
      { id: "j_23", category: "jobs", categoryLabel: "職業", jp: "運転手 / ドライバー", answer: "tài xế", altAnswers: ["tai xe"] },
      { id: "j_24", category: "jobs", categoryLabel: "職業", jp: "理容師 / 美容師", answer: "thợ cắt tóc", altAnswers: ["tho cat toc"] },
      { id: "j_25", category: "jobs", categoryLabel: "職業", jp: "仕立て屋 / 裁縫師", answer: "thợ may", altAnswers: ["tho may"] },
      { id: "j_26", category: "jobs", categoryLabel: "職業", jp: "電気技師", answer: "thợ điện", altAnswers: ["tho dien"] },
      { id: "j_27", category: "jobs", categoryLabel: "職業", jp: "大工", answer: "thợ mộc", altAnswers: ["tho moc"] },
      { id: "j_28", category: "jobs", categoryLabel: "職業", jp: "農家 / 農業従事者", answer: "nông dân", altAnswers: ["nong dan"] },
      { id: "j_29", category: "jobs", categoryLabel: "職業", jp: "漁師", answer: "ngư dân", altAnswers: ["ngu dan"] },
      { id: "j_30", category: "jobs", categoryLabel: "職業", jp: "警備員 / セキュリティ", answer: "bảo vệ", altAnswers: ["bao ve"] },
      { id: "j_31", category: "jobs", categoryLabel: "職業", jp: "ウェイター / 給仕", answer: "phục vụ", altAnswers: ["phuc vu"] },
      { id: "j_32", category: "jobs", categoryLabel: "職業", jp: "ツアーガイド", answer: "hướng dẫn viên", altAnswers: ["huong dan vien"] },
      { id: "j_33", category: "jobs", categoryLabel: "職業", jp: "建築家", answer: "kiến trúc sư", altAnswers: ["kien truc su"] },
      { id: "j_34", category: "jobs", categoryLabel: "職業", jp: "会計士", answer: "kế toán", altAnswers: ["ke toan"] },
      { id: "j_35", category: "jobs", categoryLabel: "職業", jp: "薬剤師", answer: "dược sĩ", altAnswers: ["duoc si"] },
      { id: "j_36", category: "jobs", categoryLabel: "職業", jp: "歯科医 (歯医者)", answer: "nha sĩ", altAnswers: ["nha si"] },
      { id: "j_37", category: "jobs", categoryLabel: "職業", jp: "通訳者", answer: "phiên dịch viên", altAnswers: ["phien dich vien"] },
      { id: "j_38", category: "jobs", categoryLabel: "職業", jp: "翻訳家", answer: "dịch giả", altAnswers: ["dich gia"] },
      { id: "j_39", category: "jobs", categoryLabel: "職業", jp: "科学者", answer: "nhà khoa học", altAnswers: ["nha khoa hoc"] },
      { id: "j_40", category: "jobs", categoryLabel: "職業", jp: "アスリート / 運動選手", answer: "vận động viên", altAnswers: ["van dong vien"] },
      { id: "j_41", category: "jobs", categoryLabel: "職業", jp: "実業家 / 起業家", answer: "doanh nhân", altAnswers: ["doanh nhan"] },
      { id: "j_42", category: "jobs", categoryLabel: "職業", jp: "販売員 / 店員", answer: "nhân viên bán hàng", altAnswers: ["nhan vien ban hang"] },
      { id: "j_43", category: "jobs", categoryLabel: "職業", jp: "自動車整備士", answer: "thợ sửa xe", altAnswers: ["tho sua xe"] },
      { id: "j_44", category: "jobs", categoryLabel: "職業", jp: "モデル", answer: "người mẫu", altAnswers: ["nguoi mau"] },
      { id: "j_45", category: "jobs", categoryLabel: "職業", jp: "デザイナー", answer: "nhà thiết kế", altAnswers: ["nha thiet ke"] },
      { id: "j_46", category: "jobs", categoryLabel: "職業", jp: "秘書", answer: "thư ký", altAnswers: ["thu ky"] },
      { id: "j_47", category: "jobs", categoryLabel: "職業", jp: "司書 (図書館員)", answer: "thủ thư", altAnswers: ["thu thu"] },
      { id: "j_48", category: "jobs", categoryLabel: "職業", jp: "政治家", answer: "chính trị gia", altAnswers: ["chinh tri gia"] },
      { id: "j_49", category: "jobs", categoryLabel: "職業", jp: "宇宙飛行士", answer: "phi hành gia", altAnswers: ["phi hanh gia"] },
      { id: "j_50", category: "jobs", categoryLabel: "職業", jp: "アシスタント / 助手", answer: "trợ lý", altAnswers: ["tro ly"] },

      // === CATEGORY: BUILDINGS & PLACES (50 Words) ===
      { id: "b_01", category: "buildings", categoryLabel: "建物・場所", jp: "学校", answer: "trường học", altAnswers: ["truong hoc"] },
      { id: "b_02", category: "buildings", categoryLabel: "建物・場所", jp: "病院", answer: "bệnh viện", altAnswers: ["benh vien"] },
      { id: "b_03", category: "buildings", categoryLabel: "建物・場所", jp: "銀行", answer: "ngân hàng", altAnswers: ["ngan hang"] },
      { id: "b_04", category: "buildings", categoryLabel: "建物・場所", jp: "会社 / 企業", answer: "công ty", altAnswers: ["cong ty"] },
      { id: "b_05", category: "buildings", categoryLabel: "建物・場所", jp: "郵便局", answer: "bưu điện", altAnswers: ["buu dien"] },
      { id: "b_06", category: "buildings", categoryLabel: "建物・場所", jp: "スーパーマーケット", answer: "siêu thị", altAnswers: ["sieu thi"] },
      { id: "b_07", category: "buildings", categoryLabel: "建物・場所", jp: "市場 (マーケット)", answer: "chợ", altAnswers: ["cho"] },
      { id: "b_08", category: "buildings", categoryLabel: "建物・場所", jp: "レストラン", answer: "nhà hàng", altAnswers: ["nha hang"] },
      { id: "b_09", category: "buildings", categoryLabel: "建物・場所", jp: "カフェ / 喫茶店", answer: "quán cà phê", altAnswers: ["quan ca phe"] },
      { id: "b_10", category: "buildings", categoryLabel: "建物・場所", jp: "ホテル", answer: "khách sạn", altAnswers: ["khach san"] },
      { id: "b_11", category: "buildings", categoryLabel: "建物・場所", jp: "空港", answer: "sân bay", altAnswers: ["san bay"] },
      { id: "b_12", category: "buildings", categoryLabel: "建物・場所", jp: "駅 (鉄道)", answer: "nhà ga", altAnswers: ["nha ga"] },
      { id: "b_13", category: "buildings", categoryLabel: "建物・場所", jp: "バスターミナル / バス停", answer: "bến xe", altAnswers: ["ben xe"] },
      { id: "b_14", category: "buildings", categoryLabel: "建物・場所", jp: "公園", answer: "công viên", altAnswers: ["cong vien"] },
      { id: "b_15", category: "buildings", categoryLabel: "建物・場所", jp: "博物館 / 美術館", answer: "bảo tàng", altAnswers: ["bao tang"] },
      { id: "b_16", category: "buildings", categoryLabel: "建物・場所", jp: "図書館", answer: "thư viện", altAnswers: ["thu vien"] },
      { id: "b_17", category: "buildings", categoryLabel: "建物・場所", jp: "映画館", answer: "rạp chiếu phim", altAnswers: ["rap chieu phim"] },
      { id: "b_18", category: "buildings", categoryLabel: "建物・場所", jp: "ショッピングモール", answer: "trung tâm thương mại", altAnswers: ["trung tam thuong mai"] },
      { id: "b_19", category: "buildings", categoryLabel: "建物・場所", jp: "書店 / 本屋", answer: "nhà sách", altAnswers: ["nha sach", "tiệm sách"] },
      { id: "b_20", category: "buildings", categoryLabel: "建物・場所", jp: "薬局 / ドラッグストア", answer: "nhà thuốc", altAnswers: ["nha thuoc", "tiệm thuốc"] },
      { id: "b_21", category: "buildings", categoryLabel: "建物・場所", jp: "コンビニ", answer: "cửa hàng tiện lợi", altAnswers: ["cua hang tien loi"] },
      { id: "b_22", category: "buildings", categoryLabel: "建物・場所", jp: "警察署", answer: "đồn cảnh sát", altAnswers: ["don canh sat"] },
      { id: "b_23", category: "buildings", categoryLabel: "建物・場所", jp: "消防署", answer: "trạm chữa cháy", altAnswers: ["tram chua chay"] },
      { id: "b_24", category: "buildings", categoryLabel: "建物・場所", jp: "ビル / 建築物", answer: "tòa nhà", altAnswers: ["toa nha"] },
      { id: "b_25", category: "buildings", categoryLabel: "建物・場所", jp: "マンション / アパート", answer: "chung cư", altAnswers: ["chung cu"] },
      { id: "b_26", category: "buildings", categoryLabel: "建物・場所", jp: "教会", answer: "nhà thờ", altAnswers: ["nha tho"] },
      { id: "b_27", category: "buildings", categoryLabel: "建物・場所", jp: "寺院 / お寺", answer: "chùa", altAnswers: ["chua"] },
      { id: "b_28", category: "buildings", categoryLabel: "建物・場所", jp: "大使館", answer: "đại sứ quán", altAnswers: ["dai su quan"] },
      { id: "b_29", category: "buildings", categoryLabel: "建物・場所", jp: "市役所 / 区役所", answer: "ủy ban nhân dân", altAnswers: ["uy ban nhan dan"] },
      { id: "b_30", category: "buildings", categoryLabel: "建物・場所", jp: "倉庫 / 納屋", answer: "nhà kho", altAnswers: ["nha kho"] },
      { id: "b_31", category: "buildings", categoryLabel: "建物・場所", jp: "工場", answer: "nhà máy", altAnswers: ["nha may"] },
      { id: "b_32", category: "buildings", categoryLabel: "建物・場所", jp: "オフィス / 事務所", answer: "văn phòng", altAnswers: ["van phong"] },
      { id: "b_33", category: "buildings", categoryLabel: "建物・場所", jp: "スポーツジム", answer: "phòng tập gym", altAnswers: ["phong tap gym"] },
      { id: "b_34", category: "buildings", categoryLabel: "建物・場所", jp: "スイミングプール", answer: "hồ bơi", altAnswers: ["ho boi"] },
      { id: "b_35", category: "buildings", categoryLabel: "建物・場所", jp: "競技場 / スタジアム", answer: "sân vận động", altAnswers: ["san van dong"] },
      { id: "b_36", category: "buildings", categoryLabel: "建物・場所", jp: "パン屋", answer: "tiệm bánh", altAnswers: ["tiem banh"] },
      { id: "b_37", category: "buildings", categoryLabel: "建物・場所", jp: "床屋 / 美容室", answer: "tiệm cắt tóc", altAnswers: ["tiem cat toc"] },
      { id: "b_38", category: "buildings", categoryLabel: "建物・場所", jp: "クリーニング店", answer: "tiệm giặt ủi", altAnswers: ["tiem giat ui"] },
      { id: "b_39", category: "buildings", categoryLabel: "建物・場所", jp: "食堂 / 大衆食堂", answer: "quán ăn", altAnswers: ["quan an"] },
      { id: "b_40", category: "buildings", categoryLabel: "建物・場所", jp: "駐車場", answer: "bãi đỗ xe", altAnswers: ["bai do xe"] },
      { id: "b_41", category: "buildings", categoryLabel: "建物・場所", jp: "ガソリンスタンド", answer: "cây xăng", altAnswers: ["cay xang"] },
      { id: "b_42", category: "buildings", categoryLabel: "建物・場所", jp: "テレビ局", answer: "đài truyền hình", altAnswers: ["dai truyen hinh"] },
      { id: "b_43", category: "buildings", categoryLabel: "建物・場所", jp: "農場 / 牧場", answer: "trang trại", altAnswers: ["trang trai"] },
      { id: "b_44", category: "buildings", categoryLabel: "建物・場所", jp: "動物園", answer: "vườn thú", altAnswers: ["vuon thu"] },
      { id: "b_45", category: "buildings", categoryLabel: "建物・場所", jp: "水族館", answer: "thủy cung", altAnswers: ["thuy cung"] },
      { id: "b_46", category: "buildings", categoryLabel: "建物・場所", jp: "遊園地 / テーマパーク", answer: "khu vui chơi", altAnswers: ["khu vui choi"] },
      { id: "b_47", category: "buildings", categoryLabel: "建物・場所", jp: "港 / 埠頭", answer: "cảng", altAnswers: ["cang"] },
      { id: "b_48", category: "buildings", categoryLabel: "建物・場所", jp: "ラジオ局", answer: "đài phát thanh", altAnswers: ["dai phat thanh"] },
      { id: "b_49", category: "buildings", categoryLabel: "建物・場所", jp: "研究所", answer: "viện nghiên cứu", altAnswers: ["vien nghien cuu"] },
      { id: "b_50", category: "buildings", categoryLabel: "建物・場所", jp: "裁判所", answer: "tòa án", altAnswers: ["toa an"] },

      // === OTHER CATEGORIES ===
      { id: "p1", category: "pronouns", categoryLabel: "代名詞", jp: "私 (フォーマル)", answer: "tôi", altAnswers: ["toi"] },
      { id: "p2", category: "pronouns", categoryLabel: "代名詞", jp: "あなた (同世代・友人)", answer: "bạn", altAnswers: ["ban"] },
      { id: "p3", category: "pronouns", categoryLabel: "代名詞", jp: "あなた / 彼 (年上の男性)", answer: "anh", altAnswers: [] },
      { id: "p4", category: "pronouns", categoryLabel: "代名詞", jp: "あなた / 彼女 (年上の女性)", answer: "chị", altAnswers: ["chi"] },
      { id: "p5", category: "pronouns", categoryLabel: "代名詞", jp: "私 / あなた (年下の相手)", answer: "em", altAnswers: [] },
      { id: "p6", category: "pronouns", categoryLabel: "代名詞", jp: "誰", answer: "ai", altAnswers: [] },
      { id: "p7", category: "pronouns", categoryLabel: "代名詞", jp: "何", answer: "gì", altAnswers: ["gi"] },
      { id: "p8", category: "pronouns", categoryLabel: "代名詞", jp: "どこ", answer: "đâu", altAnswers: ["dau"] },
      { id: "p9", category: "pronouns", categoryLabel: "代名詞", jp: "なぜ / どうして", answer: "tại sao", altAnswers: ["tai sao"] },

  { id: "v1", category: "verbs", categoryLabel: "動詞", jp: "行く", answer: "đi", altAnswers: [] },
  { id: "v2", category: "verbs", categoryLabel: "動詞", jp: "来る / 到着する", answer: "đến", altAnswers: [] },
  { id: "v3", category: "verbs", categoryLabel: "動詞", jp: "帰る / 戻る", answer: "về", altAnswers: [] },
  { id: "v4", category: "verbs", categoryLabel: "動詞", jp: "食べる", answer: "ăn", altAnswers: [] },
  { id: "v5", category: "verbs", categoryLabel: "動詞", jp: "飲む", answer: "uống", altAnswers: [] },
  { id: "v6", category: "verbs", categoryLabel: "動詞", jp: "話す / 言う", answer: "nói", altAnswers: [] },
  { id: "v7", category: "verbs", categoryLabel: "動詞", jp: "聞く", answer: "nghe", altAnswers: [] },
  { id: "v8", category: "verbs", categoryLabel: "動詞", jp: "見る / 観る", answer: "xem", altAnswers: [] },
  { id: "v9", category: "verbs", categoryLabel: "動詞", jp: "知っている", answer: "biết", altAnswers: [] },
  { id: "v10", category: "verbs", categoryLabel: "動詞", jp: "理解する / 分かる", answer: "hiểu", altAnswers: [] },
  { id: "v11", category: "verbs", categoryLabel: "動詞", jp: "買う", answer: "mua", altAnswers: [] },
  { id: "v12", category: "verbs", categoryLabel: "動詞", jp: "欲しい / 〜したい", answer: "muốn", altAnswers: [] },
  { id: "v13", category: "verbs", categoryLabel: "動詞", jp: "する / 作る / 働く", answer: "làm", altAnswers: [] },
  { id: "v14", category: "verbs", categoryLabel: "動詞", jp: "売る", answer: "bán", altAnswers: [] },
  { id: "v15", category: "verbs", categoryLabel: "動詞", jp: "読む", answer: "đọc", altAnswers: [] },
  { id: "v16", category: "verbs", categoryLabel: "動詞", jp: "書く", answer: "viết", altAnswers: [] },
  { id: "v17", category: "verbs", categoryLabel: "動詞", jp: "勉強する / 学ぶ", answer: "học", altAnswers: [] },
  { id: "v18", category: "verbs", categoryLabel: "動詞", jp: "教える", answer: "dạy", altAnswers: [] },
  { id: "v19", category: "verbs", categoryLabel: "動詞", jp: "寝る", answer: "ngủ", altAnswers: [] },
  { id: "v20", category: "verbs", categoryLabel: "動詞", jp: "起きる", answer: "dậy", altAnswers: [] },
  { id: "v21", category: "verbs", categoryLabel: "動詞", jp: "シャワーを浴びる", answer: "tắm", altAnswers: [] },
  { id: "v22", category: "verbs", categoryLabel: "動詞", jp: "思う / 考える", answer: "nghĩ", altAnswers: [] },
  { id: "v23", category: "verbs", categoryLabel: "動詞", jp: "覚えている / 恋しく思う", answer: "nhớ", altAnswers: [] },
  { id: "v24", category: "verbs", categoryLabel: "動詞", jp: "忘れる", answer: "quên", altAnswers: [] },
  { id: "v25", category: "verbs", categoryLabel: "動詞", jp: "好む / 好きである", answer: "thích", altAnswers: [] },
  { id: "v26", category: "verbs", categoryLabel: "動詞", jp: "愛する", answer: "yêu", altAnswers: [] },
  { id: "v27", category: "verbs", categoryLabel: "動詞", jp: "会う", answer: "gặp", altAnswers: [] },
  { id: "v28", category: "verbs", categoryLabel: "動詞", jp: "待つ", answer: "đợi", altAnswers: [] },
  { id: "v29", category: "verbs", categoryLabel: "動詞", jp: "探す", answer: "tìm", altAnswers: [] },
  { id: "v30", category: "verbs", categoryLabel: "動詞", jp: "見える / 感じる", answer: "thấy", altAnswers: [] },
  { id: "v31", category: "verbs", categoryLabel: "動詞", jp: "与える / あげる", answer: "cho", altAnswers: [] },
  { id: "v32", category: "verbs", categoryLabel: "動詞", jp: "受け取る / もらう", answer: "nhận", altAnswers: [] },
  { id: "v33", category: "verbs", categoryLabel: "動詞", jp: "必要とする", answer: "cần", altAnswers: [] },
  { id: "v34", category: "verbs", categoryLabel: "動詞", jp: "ある / 持っている", answer: "có", altAnswers: [] },
  { id: "v35", category: "verbs", categoryLabel: "動詞", jp: "住む / 生きる", answer: "sống", altAnswers: [] },
  { id: "v36", category: "verbs", categoryLabel: "動詞", jp: "居る / 滞在する", answer: "ở", altAnswers: [] },
  { id: "v37", category: "verbs", categoryLabel: "動詞", jp: "使う", answer: "dùng", altAnswers: [] },
  { id: "v38", category: "verbs", categoryLabel: "動詞", jp: "手伝う / 助ける", answer: "giúp", altAnswers: [] },
  { id: "v39", category: "verbs", categoryLabel: "動詞", jp: "尋ねる / 質問する", answer: "hỏi", altAnswers: [] },
  { id: "v40", category: "verbs", categoryLabel: "動詞", jp: "答える", answer: "trả lời", altAnswers: [] },
  { id: "v41", category: "verbs", categoryLabel: "動詞", jp: "始まる / 始める", answer: "bắt đầu", altAnswers: [] },
  { id: "v42", category: "verbs", categoryLabel: "動詞", jp: "終わる / 終了する", answer: "kết thúc", altAnswers: [] },
  { id: "v43", category: "verbs", categoryLabel: "動詞", jp: "走る", answer: "chạy", altAnswers: [] },
  { id: "v44", category: "verbs", categoryLabel: "動詞", jp: "歩く", answer: "đi bộ", altAnswers: [] },
  { id: "v45", category: "verbs", categoryLabel: "動詞", jp: "座る", answer: "ngồi", altAnswers: [] },
  { id: "v46", category: "verbs", categoryLabel: "動詞", jp: "立つ", answer: "đứng", altAnswers: [] },
  { id: "v47", category: "verbs", categoryLabel: "動詞", jp: "開ける", answer: "mở", altAnswers: [] },
  { id: "v48", category: "verbs", categoryLabel: "動詞", jp: "閉める", answer: "đóng", altAnswers: [] },
  { id: "v49", category: "verbs", categoryLabel: "動詞", jp: "払う / 返す", answer: "trả", altAnswers: [] },
  { id: "v50", category: "verbs", categoryLabel: "動詞", jp: "持っていく / 運ぶ", answer: "mang", altAnswers: [] },

  { id: "n1", category: "nouns", categoryLabel: "名詞", jp: "水", answer: "nước", altAnswers: [] },
  { id: "n2", category: "nouns", categoryLabel: "名詞", jp: "ご飯 / ごちそう", answer: "cơm", altAnswers: [] },
  { id: "n3", category: "nouns", categoryLabel: "名詞", jp: "家 / 住宅", answer: "nhà", altAnswers: [] },
  { id: "n4", category: "nouns", categoryLabel: "名詞", jp: "お金", answer: "tiền", altAnswers: [] },
  { id: "n5", category: "nouns", categoryLabel: "名詞", jp: "車 / 乗り物", answer: "xe", altAnswers: [] },
  { id: "n6", category: "nouns", categoryLabel: "名詞", jp: "時間", answer: "thời gian", altAnswers: [] },
  { id: "n7", category: "nouns", categoryLabel: "名詞", jp: "今日", answer: "hôm nay", altAnswers: [] },
  { id: "n8", category: "nouns", categoryLabel: "名詞", jp: "明日", answer: "ngày mai", altAnswers: [] },
  { id: "n9", category: "nouns", categoryLabel: "名詞", jp: "昨日", answer: "hôm qua", altAnswers: [] },
  { id: "n10", category: "nouns", categoryLabel: "名詞", jp: "友達", answer: "bạn", altAnswers: [] },
  { id: "n11", category: "nouns", categoryLabel: "名詞", jp: "人", answer: "người", altAnswers: [] },
  { id: "n12", category: "nouns", categoryLabel: "名詞", jp: "日 / 日付", answer: "ngày", altAnswers: [] },
  { id: "n13", category: "nouns", categoryLabel: "名詞", jp: "月", answer: "tháng", altAnswers: [] },
  { id: "n14", category: "nouns", categoryLabel: "名詞", jp: "年", answer: "năm", altAnswers: [] },
  { id: "n15", category: "nouns", categoryLabel: "名詞", jp: "場所 / 所", answer: "chỗ", altAnswers: [] },
  { id: "n16", category: "nouns", categoryLabel: "名詞", jp: "学校", answer: "trường", altAnswers: [] },
  { id: "n17", category: "nouns", categoryLabel: "名詞", jp: "会社", answer: "công ty", altAnswers: [] },
  { id: "n18", category: "nouns", categoryLabel: "名詞", jp: "病院", answer: "bệnh viện", altAnswers: [] },
  { id: "n19", category: "nouns", categoryLabel: "名詞", jp: "市場", answer: "chợ", altAnswers: [] },
  { id: "n20", category: "nouns", categoryLabel: "名詞", jp: "レストラン", answer: "nhà hàng", altAnswers: [] },
  { id: "n21", category: "nouns", categoryLabel: "名詞", jp: "部屋", answer: "phòng", altAnswers: [] },
  { id: "n22", category: "nouns", categoryLabel: "名詞", jp: "本", answer: "sách", altAnswers: [] },
  { id: "n23", category: "nouns", categoryLabel: "名詞", jp: "電話 / スマホ", answer: "điện thoại", altAnswers: [] },
  { id: "n24", category: "nouns", categoryLabel: "名詞", jp: "バイク", answer: "xe máy", altAnswers: [] },
  { id: "n25", category: "nouns", categoryLabel: "名詞", jp: "飛行機", answer: "máy bay", altAnswers: [] },
  { id: "n26", category: "nouns", categoryLabel: "名詞", jp: "服 / シャツ", answer: "áo", altAnswers: [] },
  { id: "n27", category: "nouns", categoryLabel: "名詞", jp: "靴", answer: "giày", altAnswers: [] },
  { id: "n28", category: "nouns", categoryLabel: "名詞", jp: "バッグ / 鞄", answer: "túi xách", altAnswers: [] },
  { id: "n29", category: "nouns", categoryLabel: "名詞", jp: "家族", answer: "gia đình", altAnswers: [] },
  { id: "n30", category: "nouns", categoryLabel: "名詞", jp: "父 / お父さん", answer: "bố", altAnswers: [] },
  { id: "n31", category: "nouns", categoryLabel: "名詞", jp: "母 / お母さん", answer: "mẹ", altAnswers: [] },
  { id: "n32", category: "nouns", categoryLabel: "名詞", jp: "子供", answer: "con", altAnswers: [] },
  { id: "n33", category: "nouns", categoryLabel: "名詞", jp: "先生 / 講師", answer: "thầy cô", altAnswers: [] },
  { id: "n34", category: "nouns", categoryLabel: "名詞", jp: "学生 / 生徒", answer: "học sinh", altAnswers: [] },
  { id: "n35", category: "nouns", categoryLabel: "名詞", jp: "仕事 / 作業", answer: "công việc", altAnswers: [] },
  { id: "n36", category: "nouns", categoryLabel: "名詞", jp: "料理 / 食べ物", answer: "món ăn", altAnswers: [] },
  { id: "n37", category: "nouns", categoryLabel: "名詞", jp: "お茶", answer: "trà", altAnswers: [] },
  { id: "n38", category: "nouns", categoryLabel: "名詞", jp: "コーヒー", answer: "cà phê", altAnswers: [] },
  { id: "n39", category: "nouns", categoryLabel: "名詞", jp: "肉", answer: "thịt", altAnswers: [] },
  { id: "n40", category: "nouns", categoryLabel: "名詞", jp: "魚", answer: "cá", altAnswers: [] },
  { id: "n41", category: "nouns", categoryLabel: "名詞", jp: "野菜", answer: "rau", altAnswers: [] },
  { id: "n42", category: "nouns", categoryLabel: "名詞", jp: "果物", answer: "trái cây", altAnswers: [] },
  { id: "n43", category: "nouns", categoryLabel: "名詞", jp: "天気", answer: "thời tiết", altAnswers: [] },
  { id: "n44", category: "nouns", categoryLabel: "名詞", jp: "雨", answer: "mưa", altAnswers: [] },
  { id: "n45", category: "nouns", categoryLabel: "名詞", jp: "晴れ / 日差し", answer: "nắng", altAnswers: [] },
  { id: "n46", category: "nouns", categoryLabel: "名詞", jp: "道 / 道路", answer: "đường", altAnswers: [] },
  { id: "n47", category: "nouns", categoryLabel: "名詞", jp: "名前", answer: "tên", altAnswers: [] },
  { id: "n48", category: "nouns", categoryLabel: "名詞", jp: "言葉 / 言語", answer: "tiếng", altAnswers: [] },
  { id: "n49", category: "nouns", categoryLabel: "名詞", jp: "写真", answer: "hình ảnh", altAnswers: [] },
  { id: "n50", category: "nouns", categoryLabel: "名詞", jp: "問題", answer: "vấn đề", altAnswers: [] },

  { id: "a1", category: "adjectives", categoryLabel: "形容詞", jp: "美味しい", answer: "ngon", altAnswers: [] },
  { id: "a2", category: "adjectives", categoryLabel: "形容詞", jp: "良い / 上級の", answer: "tốt", altAnswers: [] },
  { id: "a3", category: "adjectives", categoryLabel: "形容詞", jp: "美しい / 綺麗な", answer: "đẹp", altAnswers: [] },
  { id: "a4", category: "adjectives", categoryLabel: "形容詞", jp: "多い / たくさん", answer: "nhiều", altAnswers: [] },
  { id: "a5", category: "adjectives", categoryLabel: "形容詞", jp: "少ない", answer: "ít", altAnswers: [] },
  { id: "a6", category: "adjectives", categoryLabel: "形容詞", jp: "高い (価格)", answer: "đắt", altAnswers: [] },
  { id: "a7", category: "adjectives", categoryLabel: "形容詞", jp: "安い", answer: "rẻ", altAnswers: [] },
  { id: "a8", category: "adjectives", categoryLabel: "形容詞", jp: "忙しい", answer: "bận", altAnswers: [] },
  { id: "a9", category: "adjectives", categoryLabel: "形容詞", jp: "疲れた", answer: "mệt", altAnswers: [] },
  { id: "a10", category: "adjectives", categoryLabel: "形容詞", jp: "暑い", answer: "nóng", altAnswers: [] },
  { id: "a11", category: "adjectives", categoryLabel: "形容詞", jp: "寒い / 冷たい", answer: "lạnh", altAnswers: [] },
  { id: "a12", category: "adjectives", categoryLabel: "形容詞", jp: "涼しい", answer: "mát", altAnswers: [] },
  { id: "a13", category: "adjectives", categoryLabel: "形容詞", jp: "暖かい", answer: "ấm", altAnswers: [] },
  { id: "a14", category: "adjectives", categoryLabel: "形容詞", jp: "大きい", answer: "lớn", altAnswers: [] },
  { id: "a15", category: "adjectives", categoryLabel: "形容詞", jp: "小さい", answer: "nhỏ", altAnswers: [] },
  { id: "a16", category: "adjectives", categoryLabel: "形容詞", jp: "長い", answer: "dài", altAnswers: [] },
  { id: "a17", category: "adjectives", categoryLabel: "形容詞", jp: "短い", answer: "ngắn", altAnswers: [] },
  { id: "a18", category: "adjectives", categoryLabel: "形容詞", jp: "高い (背・高さ)", answer: "cao", altAnswers: [] },
  { id: "a19", category: "adjectives", categoryLabel: "形容詞", jp: "低い (背・高さ)", answer: "thấp", altAnswers: [] },
  { id: "a20", category: "adjectives", categoryLabel: "形容詞", jp: "重い", answer: "nặng", altAnswers: [] },
  { id: "a21", category: "adjectives", categoryLabel: "形容詞", jp: "軽い", answer: "nhẹ", altAnswers: [] },
  { id: "a22", category: "adjectives", categoryLabel: "形容詞", jp: "新しい", answer: "mới", altAnswers: [] },
  { id: "a23", category: "adjectives", categoryLabel: "形容詞", jp: "古い", answer: "cũ", altAnswers: [] },
  { id: "a24", category: "adjectives", categoryLabel: "形容詞", jp: "速い / 早い", answer: "nhanh", altAnswers: [] },
  { id: "a25", category: "adjectives", categoryLabel: "形容詞", jp: "遅い", answer: "chậm", altAnswers: [] },
  { id: "a26", category: "adjectives", categoryLabel: "形容詞", jp: "難しい", answer: "khó", altAnswers: [] },
  { id: "a27", category: "adjectives", categoryLabel: "形容詞", jp: "簡単な / 易しい", answer: "dễ", altAnswers: [] },
  { id: "a28", category: "adjectives", categoryLabel: "形容詞", jp: "楽しい / 嬉しい", answer: "vui", altAnswers: [] },
  { id: "a29", category: "adjectives", categoryLabel: "形容詞", jp: "悲しい", answer: "buồn", altAnswers: [] },
  { id: "a30", category: "adjectives", categoryLabel: "形容詞", jp: "面白い", answer: "thú vị", altAnswers: [] },
  { id: "a31", category: "adjectives", categoryLabel: "形容詞", jp: "つまらない", answer: "chán", altAnswers: [] },
  { id: "a32", category: "adjectives", categoryLabel: "形容詞", jp: "遠い", answer: "xa", altAnswers: [] },
  { id: "a33", category: "adjectives", categoryLabel: "形容詞", jp: "近い", answer: "gần", altAnswers: [] },
  { id: "a34", category: "adjectives", categoryLabel: "形容詞", jp: "綺麗な / 清潔な", answer: "sạch", altAnswers: [] },
  { id: "a35", category: "adjectives", categoryLabel: "形容詞", jp: "汚い", answer: "bẩn", altAnswers: [] },
  { id: "a36", category: "adjectives", categoryLabel: "形容詞", jp: "明るい", answer: "sáng", altAnswers: [] },
  { id: "a37", category: "adjectives", categoryLabel: "形容詞", jp: "暗い", answer: "tối", altAnswers: [] },
  { id: "a38", category: "adjectives", categoryLabel: "形容詞", jp: "強い", answer: "mạnh", altAnswers: [] },
  { id: "a39", category: "adjectives", categoryLabel: "形容詞", jp: "弱い", answer: "yếu", altAnswers: [] },
  { id: "a40", category: "adjectives", categoryLabel: "形容詞", jp: "甘い", answer: "ngọt", altAnswers: [] },
  { id: "a41", category: "adjectives", categoryLabel: "形容詞", jp: "辛い", answer: "cay", altAnswers: [] },
  { id: "a42", category: "adjectives", categoryLabel: "形容詞", jp: "しょっぱい", answer: "mặn", altAnswers: [] },
  { id: "a43", category: "adjectives", categoryLabel: "形容詞", jp: "酸っぱい", answer: "chua", altAnswers: [] },
  { id: "a44", category: "adjectives", categoryLabel: "形容詞", jp: "苦い", answer: "đắng", altAnswers: [] },
  { id: "a45", category: "adjectives", categoryLabel: "形容詞", jp: "お腹が空いた", answer: "đói", altAnswers: [] },
  { id: "a46", category: "adjectives", categoryLabel: "形容詞", jp: "お腹がいっぱい", answer: "no", altAnswers: [] },
  { id: "a47", category: "adjectives", categoryLabel: "形容詞", jp: "喉が渇いた", answer: "khát", altAnswers: [] },
  { id: "a48", category: "adjectives", categoryLabel: "形容詞", jp: "静かな", answer: "yên tĩnh", altAnswers: [] },
  { id: "a49", category: "adjectives", categoryLabel: "形容詞", jp: "うるさい / 賑やかな", answer: "ồn ào", altAnswers: [] },
  { id: "a50", category: "adjectives", categoryLabel: "形容詞", jp: "優しい", answer: "hiền", altAnswers: [] },

  // === CATEGORY: HUMAN BODY PARTS (40 Words) ===
  { id: "body_01", category: "bodyparts", categoryLabel: "体の部位", jp: "頭", answer: "đầu", altAnswers: ["dau"] },
  { id: "body_02", category: "bodyparts", categoryLabel: "体の部位", jp: "顔", answer: "mặt", altAnswers: ["mat"] },
  { id: "body_03", category: "bodyparts", categoryLabel: "体の部位", jp: "目", answer: "mắt", altAnswers: ["mat"] },
  { id: "body_04", category: "bodyparts", categoryLabel: "体の部位", jp: "耳", answer: "tai", altAnswers: ["tai"] },
  { id: "body_05", category: "bodyparts", categoryLabel: "体の部位", jp: "鼻", answer: "mũi", altAnswers: ["mui"] },
  { id: "body_06", category: "bodyparts", categoryLabel: "体の部位", jp: "口", answer: "miệng", altAnswers: ["mieng"] },
  { id: "body_07", category: "bodyparts", categoryLabel: "体の部位", jp: "歯", answer: "răng", altAnswers: ["rang"] },
  { id: "body_08", category: "bodyparts", categoryLabel: "体の部位", jp: "舌", answer: "lưỡi", altAnswers: ["luoi"] },
  { id: "body_09", category: "bodyparts", categoryLabel: "体の部位", jp: "首", answer: "cổ", altAnswers: ["co"] },
  { id: "body_10", category: "bodyparts", categoryLabel: "体の部位", jp: "肩", answer: "vai", altAnswers: ["vai"] },
  { id: "body_11", category: "bodyparts", categoryLabel: "体の部位", jp: "腕", answer: "cánh tay", altAnswers: ["canh tay"] },
  { id: "body_12", category: "bodyparts", categoryLabel: "体の部位", jp: "手", answer: "tay", altAnswers: ["tay"] },
  { id: "body_13", category: "bodyparts", categoryLabel: "体の部位", jp: "指", answer: "ngón tay", altAnswers: ["ngon tay"] },
  { id: "body_14", category: "bodyparts", categoryLabel: "体の部位", jp: "手のひら", answer: "lòng bàn tay", altAnswers: ["long ban tay"] },
  { id: "body_15", category: "bodyparts", categoryLabel: "体の部位", jp: "爪", answer: "móng tay", altAnswers: ["mong tay"] },
  { id: "body_16", category: "bodyparts", categoryLabel: "体の部位", jp: "胸", answer: "ngực", altAnswers: ["nguc"] },
  { id: "body_17", category: "bodyparts", categoryLabel: "体の部位", jp: "お腹", answer: "bụng", altAnswers: ["bung"] },
  { id: "body_18", category: "bodyparts", categoryLabel: "体の部位", jp: "背中", answer: "lưng", altAnswers: ["lung"] },
  { id: "body_19", category: "bodyparts", categoryLabel: "体の部位", jp: "腰", answer: "eo", altAnswers: ["eo"] },
  { id: "body_20", category: "bodyparts", categoryLabel: "体の部位", jp: "脚", answer: "chân", altAnswers: ["chan"] },
  { id: "body_21", category: "bodyparts", categoryLabel: "体の部位", jp: "膝", answer: "đầu gối", altAnswers: ["dau goi"] },
  { id: "body_22", category: "bodyparts", categoryLabel: "体の部位", jp: "足首", answer: "mắt cá chân", altAnswers: ["mat ca chan"] },
  { id: "body_23", category: "bodyparts", categoryLabel: "体の部位", jp: "足", answer: "bàn chân", altAnswers: ["ban chan"] },
  { id: "body_24", category: "bodyparts", categoryLabel: "体の部位", jp: "足の指", answer: "ngón chân", altAnswers: ["ngon chan"] },
  { id: "body_25", category: "bodyparts", categoryLabel: "体の部位", jp: "髪", answer: "tóc", altAnswers: ["toc"] },
  { id: "body_26", category: "bodyparts", categoryLabel: "体の部位", jp: "眉毛", answer: "lông mày", altAnswers: ["long may"] },
  { id: "body_27", category: "bodyparts", categoryLabel: "体の部位", jp: "まつ毛", answer: "lông mi", altAnswers: ["long mi"] },
  { id: "body_28", category: "bodyparts", categoryLabel: "体の部位", jp: "頬", answer: "má", altAnswers: ["ma"] },
  { id: "body_29", category: "bodyparts", categoryLabel: "体の部位", jp: "顎", answer: "cằm", altAnswers: ["cam"] },
  { id: "body_30", category: "bodyparts", categoryLabel: "体の部位", jp: "額", answer: "trán", altAnswers: ["tran"] },
  { id: "body_31", category: "bodyparts", categoryLabel: "体の部位", jp: "喉", answer: "họng", altAnswers: ["hong"] },
  { id: "body_32", category: "bodyparts", categoryLabel: "体の部位", jp: "心臓", answer: "tim", altAnswers: ["tim"] },
  { id: "body_33", category: "bodyparts", categoryLabel: "体の部位", jp: "肺", answer: "phổi", altAnswers: ["phoi"] },
  { id: "body_34", category: "bodyparts", categoryLabel: "体の部位", jp: "胃", answer: "dạ dày", altAnswers: ["da day"] },
  { id: "body_35", category: "bodyparts", categoryLabel: "体の部位", jp: "肝臓", answer: "gan", altAnswers: ["gan"] },
  { id: "body_36", category: "bodyparts", categoryLabel: "体の部位", jp: "脳", answer: "não", altAnswers: ["nao"] },
  { id: "body_37", category: "bodyparts", categoryLabel: "体の部位", jp: "骨", answer: "xương", altAnswers: ["xuong"] },
  { id: "body_38", category: "bodyparts", categoryLabel: "体の部位", jp: "筋肉", answer: "cơ bắp", altAnswers: ["co bap"] },
  { id: "body_39", category: "bodyparts", categoryLabel: "体の部位", jp: "皮膚", answer: "da", altAnswers: ["da"] },
  { id: "body_40", category: "bodyparts", categoryLabel: "体の部位", jp: "血", answer: "máu", altAnswers: ["mau"] }
];
